# vim: set nospell:

application: flask-kibble-example
version: dev
runtime: python27
api_version: 1
threadsafe: true


libraries:
- name: markupsafe
  version: "latest"

- name: setuptools
  version: "0.6c11"

- name: jinja2
  version: "2.6"

handlers:

- url: /.*
  script: address_book.web.app

