# vim: set nospell:

application: flask-kibble
version: dev
runtime: python27
api_version: 1
threadsafe: true


libraries:
- name: markupsafe
  version: "latest"

- name: setuptools
  version: "0.6c11"

- name: jinja2
  version: "2.6"

handlers:

- url: /static
  static_dir: static/
  expiration: 7d

- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /.*
  script: example.web.app

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?index\.yaml
  - ^(.*/)?index\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?.*\.(bak|scss)$
  - ^(.*/)?stylesource
  - ^(.*/)?tests/.*
  - ^(.*/)?env/.*
  - ^(.*/)?google_appengine/.*

